FROM jenkins/jenkins:2.204.5

RUN /usr/local/bin/install-plugins.sh ssh-slaves
RUN /usr/local/bin/install-plugins.sh kubernetes

USER root
RUN apt-get update && apt-get install -y maven

USER jenkins
