  - name: Enable Apache rewrite module (required for Drupal).
    apache2_module: name=rewrite state=present
    notify: restart apache

  - name: Add Apache virtualhost for Drupal 8 development.
    template:
68 src: "templates/drupal.test.conf.j2"
69 dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
70 owner: root
71 group: root
72 mode: 0644
73 notify: restart apache
74
75 - name: Symlink Drupal virtualhost to sites-enabled.
76 file:

77 src: "/etc/apache2/sites-available/{{ domain }}.test.conf"
78 dest: "/etc/apache2/sites-enabled/{{ domain }}.test.conf"
79 state: link
80 notify: restart apache
81
82 - name: Remove default virtualhost file.
83 file:
84 path: "/etc/apache2/sites-enabled/000-default.conf"
85 state: absent
86 notify: restart apache
