#Print statements during execution
Example that prints the loopback address and gateway for each host
- debug:
   msg: System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}

- debug:
   msg: System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}
 when: ansible_default_ipv4.gateway is defined

# Example that prints return information from the previous task
- shell: /usr/bin/uptime
 register: result

- debug:
   var: result
   verbosity: 2

- name: Display all variables/facts known for a host
 debug:
   var: hostvars[inventory_hostname]
   verbosity: 4

# Example that prints two lines of messages, but only if there is an environment value set
- debug:
   msg:
   - "Provisioning based on YOUR_KEY which is: {{ lookup('env', 'YOUR_KEY') }}"
   - "These servers were built using the password of '{{ password_used }}'. Please retain this for later use."
